# Generated by Django 6.0.4 on 2026-04-20 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSV_Object',
            fields=[
                ('index', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_id', models.CharField(max_length=15)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('phone_1', models.CharField(max_length=50)),
                ('phone_2', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('subscription_date', models.DateField()),
                ('website', models.URLField()),
            ],
        ),
    ]
